export const translations = {
  ar: {
    settings: 'الإعدادات',
    darkMode: 'الوضع الليلي',
    darkModeOn: 'مفعل',
    darkModeOff: 'معطل',
    language: 'اللغة',
    clearData: 'حذف البيانات والتخزين',
    aboutApp: 'عن التطبيق',
    aboutIkyro: 'عن iKyro',
    privacy: 'سياسة الخصوصية',
    terms: 'الشروط والأحكام',
    favorites: 'المفضلة',
    downloads: 'التنزيلات',
    home: 'الرئيسية',
    games: 'الألعاب',
    apps: 'التطبيقات',
    search: 'بحث',
    areYouSure: 'هل أنت متأكد من حذف البيانات؟',
    cancel: 'إلغاء',
    delete: 'حذف',
    ok: 'حسناً',
    alert: 'تنبيه',
    cannotInstall: 'لا يمكنك تثبيت هذا التطبيق حالياً',
    downloadHistory: 'سجل التنزيلات',
    localDownloaded: 'التطبيقات المحملة محلياً',
    noDownloads: 'لا توجد تنزيلات سابقة.',
    recently: 'مؤخراً',
    discover: 'اكتشف',
    appsAndGames: 'التطبيقات والألعاب',
    carefullySelected: 'مجموعة مختارة بعناية',
    categoriesTitle: 'الأقسام',
    modded: 'مهكرة',
    recommended: 'موصى بك',
    topApps: 'أفضل التطبيقات',
    featuredGames: 'الألعاب المميزة',
    trending: 'الأكثر شهرة',
    moddedGames: 'ألعاب مهكرة',
    aiApps: 'تطبيقات الذكاء الاصطناعي',
    offlineGames: 'ألعاب بدون نت',
    onlineGames: 'ألعاب أونلاين',
    noAppsFound: 'لا توجد تطبيقات',
    noAppsDesc: 'لم يتم العثور على أي تطبيقات في هذا القسم حالياً.',
    all: 'الكل',
    changeLanguageConfirm: 'هل أنت متأكد من تغيير اللغة؟',
    yes: 'نعم',
    no: 'لا',
    version: 'الإصدار',
    appUpdate: 'تحديث التطبيق',
    currentVersion: 'النسخة الحالية',
    appUpToDate: 'التطبيق بأحدث إصدار',
    updateAvailable: 'يتوفر تحديث جديد',
    checkForUpdates: 'التحقق من وجود تحديثات',
    size: 'الحجم',
    downloadsCount: 'التثبيتات',
    description: 'الوصف',
    download: 'تثبيت',
    requirements: 'المتطلبات',
    category: 'الفئة',
    modification: 'تعديل',
    shareApp: 'مشاركة التطبيق',
    reportProblem: 'الإبلاغ عن مشكلة',
    selectProblemType: 'اختر نوع المشكلة',
    problemTypes: {
      appIssue: 'مشكلة في التطبيق',
      featureSuggestion: 'اقتراح ميزة',
      downloadIssue: 'مشكلة في تثبيت لعبة/تطبيق',
      other: 'أخرى'
    },
    problemDescriptions: {
      appIssue: 'يرجى وصف المشكلة التي واجهتك في التطبيق بالتفصيل لكي نتمكن من حلها في أسرع وقت.',
      featureSuggestion: 'نحن نقدر أفكارك! ما الميزة التي تود أن تراها في التطبيق؟',
      downloadIssue: 'ما هو التطبيق أو اللعبة التي تواجه مشكلة في تثبيتها؟ وما هو الخطأ الذي يظهر لك؟',
      other: 'يرجى كتابة رسالتك بوضوح وسنقوم بالرد عليك في أقرب وقت.'
    },
    reportTemplate: 'مرحباً فريق دعم iKyro،\n\nأواجه المشكلة التالية:\n[اكتب مشكلتك هنا]\n\nالاسم: [اسمك]',
    shareAppText: 'نزل تطبيق iKyro واستمتع بأفضل التطبيقات والألعاب! جربه الآن من هذا الرابط:',
    official: 'رسمي',
    recommendedForYou: 'موصى به',
    viewAllResults: 'عرض جميع النتائج لـ',
    noQuickResults: 'لا توجد نتائج سريعة',
    comprehensiveSearch: 'البحث الشامل',
    viewFavorites: 'عرض المفضلة',
    addedToFavorites: 'تم الإضافة إلى المفضلة',
    removedFromFavorites: 'تم الإزالة من المفضلة',
    responseSent: 'تم ارسال ردك',
    moreFromPublisher: 'المزيد من الناشر',
    yourFavoriteApps: 'تطبيقاتك وألعابك المفضلة',
    noFavoritesYet: 'لا توجد تطبيقات في المفضلة بعد.',
    searchForAnythingNew: 'ابحث عن كل ما هو جديد',
    exploreThousandsOfApps: 'استكشف آلاف التطبيقات والألعاب، وحملها بضغطة زر واحدة.',
    recentSearches: 'عمليات البحث الأخيرة',
    clearHistory: 'مسح السجل',
    quickResults: 'نتائج سريعة',
    searchResults: 'نتائج البحث',
    noResultsFound: 'لم يتم العثور على نتائج',
    tryOtherKeywords: 'جرب كلمات مفتاحية أخرى',
    downloadLinkNotFound: 'تعذر العثور على رابط التثبيت المباشر.',
    downloadError: 'حدث خطأ أثناء جلب رابط التثبيت.',
    dataWillBeDeleted: 'سيتم حذف جميع التطبيقات المفضلة وسجل البحث والتثبيتات. لا يمكن التراجع عن هذا الإجراء.',
    howWeUseInfo: 'كيف نستخدم المعلومات؟',
    howWeUseInfoDesc: 'نستخدم هذه المعلومات فقط لتخصيص تجربتك داخل التطبيق وتسهيل وصولك إلى المحتوى الذي تفضله. لا نقوم بمشاركة أي من بياناتك مع أطراف ثالثة.',
    acceptableUse: 'الاستخدام المقبول',
    acceptableUseDesc: 'يجب استخدام التطبيق للأغراض المشروعة فقط. يمنع منعاً باتاً أي محاولة للتلاعب بالنظام أو التحايل على حقوق الملكية الفكرية للتطبيقات والألعاب المتاحة.',
    disclaimer: 'إخلاء المسؤولية',
    disclaimerDesc: 'نحن نبذل قصارى جهدنا لضمان جودة وأمان المحتوى، ولكننا لا نتحمل المسؤولية عن أي أضرار قد تنتج عن استخدام التطبيقات أو الألعاب المحملة من خلال المنصة.',
    termsIntro: 'باستخدامك لتطبيق iKyro، فإنك توافق على الشروط والأحكام التالية. يرجى قراءتها بعناية.',
    aboutDescription: 'نحن في iKyro نهدف إلى توفير منصة آمنة وسريعة لتثبيت وتجربة أفضل التطبيقات والألعاب. نسعى دائماً لتقديم تجربة مستخدم سلسة وعصرية تلبي احتياجاتك.',
    featuresListTitle: 'مميزات المنصة',
    features: [
      'تطبيقات وألعاب آمنة ومفحوصة',
      'تحديثات مستمرة وتلقائية',
      'واجهة مستخدم عصرية وسريعة',
      'ألعاب سريعة (Instant Games)',
      'وضع نهاري وليلي (Dark & Light Mode)',
      'تنزيلات وتحميل سريع (Fast Downloads)',
      'تصفح الألعاب والتطبيقات (Browse Apps & Games)',
      'مكتبة المفضلة (Favorites Library)',
      'البحث الذكي الشامل (Smart Search)',
      'دعم اللغات (Multi-language Support)'
    ],
    privacyIntro: 'نحن في iKyro نقدر خصوصيتك ونلتزم بحماية بياناتك الشخصية. هذه السياسة توضح كيفية تعاملنا مع المعلومات.',
    dataCollection: 'جمع البيانات',
    dataCollectionDesc: 'التطبيق لا يقوم بجمع أي بيانات شخصية حساسة. نقوم فقط بحفظ تفضيلاتك (مثل المفضلة، وسجل التثبيتات، واللغة) محلياً على جهازك لضمان تجربة مستخدم أفضل.',
    categoryNames: {
      'الألعاب': 'الألعاب',
      'التطبيقات': 'التطبيقات',
      'الأكثر تثبيتاً': 'الأكثر تثبيتاً',
      'الأكثر شهرة': 'الأكثر شهرة',
      'الجديدة': 'الجديدة',
      'المميزة': 'المميزة',
      'Premium': 'Premium',
      'الذكاء الاصطناعي': 'الذكاء الاصطناعي',
      'الفيديو': 'الفيديو',
      'الموسيقى': 'الموسيقى',
      'التصوير': 'التصوير',
      'التصميم': 'التصميم',
      'الأمن': 'الأمن',
      'الأدوات': 'الأدوات',
      'النظام': 'النظام',
      'المحاكيات': 'المحاكيات',
      'التعليم': 'التعليم',
      'التواصل': 'التواصل',
      'المتصفحات': 'المتصفحات',
      'التخزين': 'التخزين'
    },
    subcats: {
      'أكشن': 'أكشن', 'أركيد': 'أركيد', 'سباق': 'سباق', 'محاكاة': 'محاكاة', 'رياضة': 'رياضة', 
      'استراتيجية': 'استراتيجية', 'تقمص أدوار': 'تقمص أدوار', 'ألغاز': 'ألغاز', 'ألعاب خفيفة': 'ألعاب خفيفة', 
      'مغامرة': 'مغامرة', 'لوحة': 'لوحة', 'ورق': 'ورق', 'كازينو': 'كازينو', 'موسيقى': 'موسيقى', 'كلمات': 'كلمات',
      'أدوات': 'أدوات', 'تواصل': 'تواصل', 'تصوير': 'تصوير', 'فيديو': 'فيديو', 'إنتاجية': 'إنتاجية', 
      'تخصيص': 'تخصيص', 'نمط حياة': 'نمط حياة', 'فن وتصميم': 'فن وتصميم', 'تصميم': 'تصميم', 'أمن': 'أمن', 
      'نظام': 'نظام', 'محاكيات': 'محاكيات', 'متصفحات': 'متصفحات', 'تخزين': 'تخزين', 'أعمال': 'أعمال', 
      'ترفيه': 'ترفيه', 'مال': 'مال', 'صحة ولياقة': 'صحة ولياقة', 'طب': 'طب', 'أخبار': 'أخبار', 
      'طقس': 'طقس', 'تسوّق': 'تسوّق', 'سفر': 'سفر', 'تعليم': 'تعليم'
    },
    onboardingWelcome: 'مرحباً بك في iKyro!',
    onboardingNavDesc: 'استخدم شريط التنقل السفلي للتبديل بسرعة بين الألعاب والتطبيقات والبحث والملف الشخصي.',
    onboardingSearchDesc: 'ابحث عن تطبيقاتك وألعابك المفضلة فوراً باستخدام محرك البحث الشامل.',
    onboardingNext: 'التالي',
    onboardingDone: 'فهمت!',
    exitConfirmTitle: 'الخروج من التطبيق',
    exitConfirmDesc: 'هل أنت متأكد أنك تريد الخروج؟',
    exitConfirmYes: 'خروج',
    exitConfirmNo: 'إلغاء',
    instantGames: 'ألعاب سريعة',
    playNow: 'العب الآن',
    ticTacToe: 'تيك تاك تو',
    simonSays: 'تتبع الألوان',
    memoryGame: 'لعبة الذاكرة',
    starCatcher: 'صائد النجوم',
    rockPaperScissors: 'حجر ورقة مقص',
    youWin: 'لقد فزت!',
    youLose: 'لقد خسرت!',
    draw: 'تعادل!'
  },
  en: {
    settings: 'Settings',
    darkMode: 'Dark Mode',
    darkModeOn: 'On',
    darkModeOff: 'Off',
    language: 'Language',
    clearData: 'Clear Data & Storage',
    aboutApp: 'About App',
    aboutIkyro: 'About iKyro',
    privacy: 'Privacy Policy',
    terms: 'Terms & Conditions',
    favorites: 'Favorites',
    downloads: 'Downloads',
    home: 'Home',
    games: 'Games',
    apps: 'Apps',
    search: 'Search',
    areYouSure: 'Are you sure you want to clear data?',
    cancel: 'Cancel',
    delete: 'Delete',
    ok: 'OK',
    alert: 'Alert',
    cannotInstall: 'You cannot install this app currently',
    downloadHistory: 'Download History',
    localDownloaded: 'Locally downloaded apps',
    noDownloads: 'No previous downloads.',
    recently: 'Recently',
    discover: 'Discover',
    appsAndGames: 'Apps and Games',
    carefullySelected: 'Carefully selected collection',
    categoriesTitle: 'Categories',
    modded: 'Modded',
    recommended: 'Recommended for you',
    topApps: 'Top Apps',
    featuredGames: 'Featured Games',
    trending: 'Trending',
    moddedGames: 'Modded Games',
    aiApps: 'AI Apps',
    offlineGames: 'Offline Games',
    onlineGames: 'Online Games',
    noAppsFound: 'No Apps Found',
    noAppsDesc: 'No apps were found in this section currently.',
    all: 'All',
    changeLanguageConfirm: 'Are you sure you want to change language?',
    yes: 'Yes',
    no: 'No',
    version: 'Version',
    appUpdate: 'App Update',
    currentVersion: 'Current Version',
    appUpToDate: 'App is up to date',
    updateAvailable: 'Update available',
    checkForUpdates: 'Check for updates',
    size: 'Size',
    downloadsCount: 'Downloads',
    description: 'Description',
    download: 'Download',
    requirements: 'Requirements',
    category: 'Category',
    modification: 'Modification',
    shareApp: 'Share App',
    reportProblem: 'Report a Problem',
    selectProblemType: 'Select Problem Type',
    problemTypes: {
      appIssue: 'App Issue',
      featureSuggestion: 'Feature Suggestion',
      downloadIssue: 'Game/App Download Issue',
      other: 'Other'
    },
    problemDescriptions: {
      appIssue: 'Please describe the issue you encountered in the app in detail so we can fix it as soon as possible.',
      featureSuggestion: 'We value your ideas! What feature would you like to see in the app?',
      downloadIssue: 'Which app or game are you having trouble installing? What error is shown?',
      other: 'Please write your message clearly and we will respond as soon as possible.'
    },
    reportTemplate: 'Hello iKyro Support Team,\n\nI am facing the following issue:\n[Write your issue here]\n\nName: [Your name]',
    shareAppText: 'Download the iKyro app and enjoy the best apps and games! Get it now from this link:',
    official: 'Official',
    recommendedForYou: 'Recommended for you',
    viewAllResults: 'View all results for',
    noQuickResults: 'No quick results',
    comprehensiveSearch: 'Comprehensive Search',
    viewFavorites: 'View Favorites',
    addedToFavorites: 'Added to favorites',
    removedFromFavorites: 'Removed from favorites',
    responseSent: 'Your response has been sent',
    moreFromPublisher: 'More from publisher',
    yourFavoriteApps: 'Your favorite apps and games',
    noFavoritesYet: 'No apps in favorites yet.',
    searchForAnythingNew: 'Search for anything new',
    exploreThousandsOfApps: 'Explore thousands of apps and games, and download them with one click.',
    recentSearches: 'Recent Searches',
    clearHistory: 'Clear History',
    quickResults: 'Quick Results',
    searchResults: 'Search Results',
    noResultsFound: 'No results found',
    tryOtherKeywords: 'Try other keywords',
    downloadLinkNotFound: 'Could not find the direct download link.',
    downloadError: 'An error occurred while fetching the download link.',
    dataWillBeDeleted: 'All favorite apps, search history, and downloads will be deleted. This action cannot be undone.',
    howWeUseInfo: 'How we use information?',
    howWeUseInfoDesc: 'We only use this information to personalize your experience within the app and facilitate access to your preferred content. We do not share your data with third parties.',
    acceptableUse: 'Acceptable Use',
    acceptableUseDesc: 'The application must be used for legitimate purposes only. Any attempt to manipulate the system or bypass intellectual property rights of available apps and games is strictly prohibited.',
    disclaimer: 'Disclaimer',
    disclaimerDesc: 'We do our best to ensure the quality and safety of content, but we are not responsible for any damages resulting from using the apps or games downloaded through the platform.',
    termsIntro: 'By using the iKyro app, you agree to the following terms and conditions. Please read them carefully.',
    aboutDescription: 'We at iKyro aim to provide a safe and fast platform to download and experience the best apps and games. We constantly strive to provide a modern user experience that meets your needs.',
    featuresListTitle: 'Platform Features',
    features: [
      'Safe and scanned apps & games',
      'Continuous and automatic updates',
      'Modern and fast UI',
      'Instant Games',
      'Dark & Light Mode',
      'Fast Downloads',
      'Browse Apps & Games',
      'Favorites Library',
      'Smart Search',
      'Multi-language Support'
    ],
    privacyIntro: 'At iKyro, we value your privacy and are committed to protecting your personal data. This policy explains how we handle your information.',
    dataCollection: 'Data Collection',
    dataCollectionDesc: 'The application does not collect any sensitive personal data. We only save your preferences (such as favorites, download history, and language) locally on your device to ensure a better user experience.',
    categoryNames: {
      'الألعاب': 'Games',
      'التطبيقات': 'Apps',
      'الأكثر تثبيتاً': 'Top Downloaded',
      'الأكثر شهرة': 'Trending',
      'الجديدة': 'New',
      'المميزة': 'Featured',
      'Premium': 'Premium',
      'الذكاء الاصطناعي': 'AI',
      'الفيديو': 'Video',
      'الموسيقى': 'Music',
      'التصوير': 'Photography',
      'التصميم': 'Design',
      'الأمن': 'Security',
      'الأدوات': 'Tools',
      'النظام': 'System',
      'المحاكيات': 'Emulators',
      'التعليم': 'Education',
      'التواصل': 'Social',
      'المتصفحات': 'Browsers',
      'التخزين': 'Storage'
    },
    subcats: {
      'أكشن': 'Action', 'أركيد': 'Arcade', 'سباق': 'Racing', 'محاكاة': 'Simulation', 'رياضة': 'Sports', 
      'استراتيجية': 'Strategy', 'تقمص أدوار': 'RPG', 'ألغاز': 'Puzzle', 'ألعاب خفيفة': 'Casual', 
      'مغامرة': 'Adventure', 'لوحة': 'Board', 'ورق': 'Card', 'كازينو': 'Casino', 'موسيقى': 'Music', 'كلمات': 'Word',
      'أدوات': 'Tools', 'تواصل': 'Social', 'تصوير': 'Photography', 'فيديو': 'Video Players', 'إنتاجية': 'Productivity', 
      'تخصيص': 'Personalization', 'نمط حياة': 'Lifestyle', 'فن وتصميم': 'Art & Design', 'تصميم': 'Design', 'أمن': 'Security', 
      'نظام': 'System', 'محاكيات': 'Emulators', 'متصفحات': 'Browsers', 'تخزين': 'Storage', 'أعمال': 'Business', 
      'ترفيه': 'Entertainment', 'مال': 'Finance', 'صحة ولياقة': 'Health & Fitness', 'طب': 'Medical', 'أخبار': 'News', 
      'طقس': 'Weather', 'تسوّق': 'Shopping', 'سفر': 'Travel', 'تعليم': 'Educational'
    },
    onboardingWelcome: 'Welcome to iKyro!',
    onboardingNavDesc: 'Use the bottom navigation to quickly switch between Games, Apps, Search, and your Profile.',
    onboardingSearchDesc: 'Find your favorite apps and games instantly using our comprehensive search.',
    onboardingNext: 'Next',
    onboardingDone: 'Got it!',
    exitConfirmTitle: 'Exit App',
    exitConfirmDesc: 'Are you sure you want to exit?',
    exitConfirmYes: 'Exit',
    exitConfirmNo: 'Cancel',
    instantGames: 'Instant Games',
    playNow: 'Play Now',
    ticTacToe: 'Tic Tac Toe',
    simonSays: 'Simon Says',
    memoryGame: 'Memory Game',
    starCatcher: 'Star Catcher',
    rockPaperScissors: 'Rock Paper Scissors',
    youWin: 'You Win!',
    youLose: 'You Lose!',
    draw: 'Draw!'
  },
  ku: {
    settings: 'ڕێکخستنەکان',
    darkMode: 'دۆخی تاریک',
    darkModeOn: 'چالاکە',
    darkModeOff: 'ناچالاکە',
    language: 'زمان',
    clearData: 'سڕینەوەی داتا و خەزن',
    aboutApp: 'دەربارەی بەرنامە',
    aboutIkyro: 'دەربارەی iKyro',
    privacy: 'سیاسەتی تایبەتمەندی',
    terms: 'مەرج و ڕێساکان',
    favorites: 'دڵخوازەکان',
    downloads: 'داگیراوەکان',
    home: 'سەرەکی',
    games: 'یارییەکان',
    apps: 'بەرنامەکان',
    search: 'گەڕان',
    areYouSure: 'ئایا دڵنیای لە سڕینەوەی داتاکان؟',
    cancel: 'هەڵوەشاندنەوە',
    delete: 'سڕینەوە',
    ok: 'باشە',
    alert: 'ئاگاداری',
    cannotInstall: 'لە ئێستادا ناتوانیت ئەم بەرنامەیە دابەزێنیت',
    downloadHistory: 'مێژووی داگرتنەکان',
    localDownloaded: 'بەرنامە داگیراوەکانی ناوخۆ',
    noDownloads: 'هیچ داگرتنێکی پێشوو نییە.',
    recently: 'لەم دواییانەدا',
    discover: 'بیدۆزەرەوە',
    appsAndGames: 'بەرنامە و یارییەکان',
    carefullySelected: 'کۆمەڵەیەکی هەڵبژێردراو',
    categoriesTitle: 'بەشەکان',
    modded: 'هاککراو',
    recommended: 'پێشنیارکراو بۆ تۆ',
    topApps: 'باشترین بەرنامەکان',
    featuredGames: 'یارییە هەڵبژێردراوەکان',
    trending: 'پڕباوترین',
    moddedGames: 'یارییە هاککراوەکان',
    aiApps: 'بەرنامەکانی ژیری دەستکرد',
    offlineGames: 'یاری بێ ئینتەرنێت',
    onlineGames: 'یاری ئۆنلاین',
    noAppsFound: 'هیچ بەرنامەیەک نەدۆزرایەوە',
    noAppsDesc: 'لە ئێستادا هیچ بەرنامەیەک لەم بەشەدا نییە.',
    all: 'هەموو',
    changeLanguageConfirm: 'ئایا دڵنیای لە گۆڕینی زمان؟',
    yes: 'بەڵێ',
    no: 'نەخێر',
    version: 'وەشان',
    appUpdate: 'نوێکردنەوەی بەرنامە',
    currentVersion: 'وەشانی ئێستا',
    appUpToDate: 'بەرنامەکە لە دوایین وەشانە',
    updateAvailable: 'نوێکردنەوە بەردەستە',
    checkForUpdates: 'پشکنین بۆ نوێکردنەوەکان',
    size: 'قەبارە',
    downloadsCount: 'داگرتنەکان',
    description: 'وەسف',
    download: 'داگرتن',
    requirements: 'پێداویستییەکان',
    category: 'بەش',
    modification: 'گۆڕانکاری',
    shareApp: 'هاوبەشکردنی بەرنامە',
    reportProblem: 'ڕاپۆرتکردنی کێشە',
    selectProblemType: 'جۆری کێشە هەڵبژێرە',
    problemTypes: {
      appIssue: 'کێشە لە بەرنامە',
      featureSuggestion: 'پێشنیاری تایبەتمەندی',
      downloadIssue: 'کێشە لە داگرتنی یاری/بەرنامە',
      other: 'تر'
    },
    problemDescriptions: {
      appIssue: 'تکایە بە وردی وەسفی ئەو کێشەیە بکە کە لە بەرنامەکەدا ڕووبەڕووت بووەتەوە بۆ ئەوەی زوو چارەسەری بکەین.',
      featureSuggestion: 'ئێمە بیرۆکەکانت بەرز دەنرخێنین! چ تایبەتمەندییەک حەز دەکەیت ببینیت لەم بەرنامەیەدا؟',
      downloadIssue: 'کام بەرنامە یان یاری کێشەی دابەزاندنی هەیە؟ چی هەڵەیەک پیشان دەدات؟',
      other: 'تکایە بە ڕوونی پەیامەکەت بنووسە و لە زووترین کاتدا وەڵامت دەدەینەوە.'
    },
    reportTemplate: 'سڵاو تیمی پشتیوانی iKyro،\n\nڕووبەڕووی ئەم کێشەیە بوومەتەوە:\n[کێشەکەت لێرە بنووسە]\n\nناو: [ناوەکەت]',
    shareAppText: 'بەرنامەی iKyro دابەزێنە و چێژ لە باشترین بەرنامە و یارییەکان ببینە! ئێستا لەم بەستەرەوە تاقیبکەرەوە:',
    official: 'فەرمی',
    recommendedForYou: 'پێشنیارکراو بۆ تۆ',
    viewAllResults: 'پیشاندانی هەموو ئەنجامەکان بۆ',
    noQuickResults: 'هیچ ئەنجامێکی خێرا نییە',
    comprehensiveSearch: 'گەڕانی گشتگیر',
    viewFavorites: 'پیشاندانی دڵخوازەکان',
    addedToFavorites: 'زیادکرا بۆ دڵخوازەکان',
    removedFromFavorites: 'سڕدرایەوە لە دڵخوازەکان',
    responseSent: 'وەڵامەکەت نێردرا',
    moreFromPublisher: 'زیاتر لە بڵاوکار',
    yourFavoriteApps: 'بەرنامە و یارییە دڵخوازەکانت',
    noFavoritesYet: 'تا ئێستا هیچ بەرنامەیەک لە دڵخوازەکاندا نییە.',
    searchForAnythingNew: 'گەڕان بۆ هەر شتێکی نوێ',
    exploreThousandsOfApps: 'بگەڕێ بەناو هەزاران بەرنامە و یاری، و بە یەک کلیک دایانگرە.',
    recentSearches: 'گەڕانەکانی دوایی',
    clearHistory: 'سڕینەوەی مێژوو',
    quickResults: 'ئەنجامی خێرا',
    searchResults: 'ئەنجامەکانی گەڕان',
    noResultsFound: 'هیچ ئەنجامێک نەدۆزرایەوە',
    tryOtherKeywords: 'وشەی تری گەڕان تاقی بکەرەوە',
    downloadLinkNotFound: 'نەتوانرا بەستەری داگرتنی ڕاستەوخۆ بدۆزرێتەوە.',
    downloadError: 'هەڵەیەک ڕوویدا لە کاتی هێنانی بەستەری داگرتن.',
    dataWillBeDeleted: 'هەموو بەرنامە دڵخوازەکان، مێژووی گەڕان و داگرتنەکان دەسڕێنەوە. ئەم کردارە گەڕانەوەی بۆ نییە.',
    howWeUseInfo: 'چۆن زانیارییەکان بەکاردەهێنین؟',
    howWeUseInfoDesc: 'ئێمە تەنها ئەم زانیارییانە بەکاردەهێنین بۆ باشترکردنی ئەزموونەکەت لەناو بەرنامەکەدا. ئێمە زانیارییەکانت لەگەڵ هیچ لایەنێکی سێیەم هاوبەش ناکەین.',
    acceptableUse: 'بەکارهێنانی ڕێگەپێدراو',
    acceptableUseDesc: 'دەبێت بەرنامەکە تەنها بۆ مەبەستی یاسایی بەکاربهێنرێت. هەر هەوڵێک بۆ فێڵکردن لە سیستەمەکە یان پێشێلکردنی مافی خاوەندارێتی قەدەغەیە.',
    disclaimer: 'لابردنی بەرپرسیارێتی',
    disclaimerDesc: 'ئێمە هەموو هەوڵێک دەدەین بۆ دڵنیابوون لە کوالێتی و سەلامەتی ناوەڕۆک، بەڵام بەرپرسیار نین لە هەر زیانێک کە بەهۆی بەکارهێنانی بەرنامەکانەوە ڕووبدات.',
    termsIntro: 'بە بەکارهێنانی بەرنامەی iKyro، تۆ ڕازی دەبیت بەم مەرج و ڕێسایانەی خوارەوە. تکایە بە وردی بیانخوێنەرەوە.',
    aboutDescription: 'ئێمە لە iKyro ئامانجمان ئەوەیە پلاتفۆرمێکی سەلامەت و خێرا دابین بکەین بۆ داگرتن و تاقیکردنەوەی باشترین بەرنامە و یارییەکان. بەردەوام هەوڵ دەدەین ئەزموونێکی سەردەمیانە پێشکەش بکەین کە لەگەڵ پێداویستییەکانت گونجاو بێت.',
    featuresListTitle: 'تایبەتمەندییەکانی پلاتفۆرم',
    features: [
      'بەرنامە و یاری سەلامەت و پشکنراو',
      'نوێکردنەوەی بەردەوام و خۆکار',
      'ڕووکارێکی سەردەمیانە و خێرا',
      'یارییە خێراکان (Instant Games)',
      'دۆخی تاریک و ڕووناک (Dark & Light Mode)',
      'داگرتنی خێرا (Fast Downloads)',
      'گەڕان بەناو بەرنامە و یارییەکاندا (Browse Apps & Games)',
      'کتێبخانەی دڵخوازەکان (Favorites Library)',
      'گەڕانی زیرەک (Smart Search)',
      'پشتیوانی فرە زمان (Multi-language Support)'
    ],
    privacyIntro: 'ئێمە لە iKyro ڕێز لە تایبەتمەندێتیت دەگرین و پابەندین بە پاراستنی داتاکانت. ئەم سیاسەتە ڕوونی دەکاتەوە چۆن مامەڵە لەگەڵ زانیارییەکانت دەکەین.',
    dataCollection: 'کۆکردنەوەی داتا',
    dataCollectionDesc: 'ئەم بەرنامەیە هیچ داتایەکی کەسی هەستیار کۆناکاتەوە. تەنها هەڵبژاردەکانت (وەک دڵخوازەکان، مێژووی داگرتن، و زمان) لەسەر ئامێرەکەت هەڵدەگرێت بۆ دابینکردنی ئەزموونێکی باشتر.',
    categoryNames: {
      'الألعاب': 'یارییەکان',
      'التطبيقات': 'بەرنامەکان',
      'الأكثر تثبيتاً': 'زۆرترین داگرتن',
      'الأكثر شهرة': 'پڕباوترین',
      'الجديدة': 'نوێ',
      'المميزة': 'هەڵبژێردراو',
      'Premium': 'پریمیەم',
      'الذكاء الاصطناعي': 'ژیری دەستکرد',
      'الفيديو': 'ڤیدیۆ',
      'الموسيقى': 'مۆسیقا',
      'التصوير': 'وێنەگرتن',
      'التصميم': 'دیزاین',
      'الأمن': 'ئاسایش',
      'الأدوات': 'ئامرازەکان',
      'النظام': 'سیستەم',
      'المحاكيات': 'لێکچووەکان',
      'التعليم': 'پەروەردە',
      'التواصل': 'پەیوەندی',
      'المتصفحات': 'وێبگەڕەکان',
      'التخزين': 'هەڵگرتن'
    },
    subcats: {
      'أكشن': 'ئاکشن', 'أركيد': 'ئارکەید', 'سباق': 'پێشبڕکێ', 'محاكاة': 'لێکچوون', 'رياضة': 'وەرزش', 
      'استراتيجية': 'ستراتیژی', 'تقمص أدوار': 'ڕۆڵگێڕان', 'ألغاز': 'مەتەڵ', 'ألعاب خفيفة': 'سوک', 
      'مغامرة': 'سەرکێشی', 'لوحة': 'تەختە', 'ورق': 'کارت', 'كازينو': 'کازینۆ', 'موسيقى': 'مۆسیقا', 'كلمات': 'وشە',
      'أدوات': 'ئامرازەکان', 'تواصل': 'پەیوەندی', 'تصوير': 'وێنەگرتن', 'فيديو': 'ڤیدیۆ', 'إنتاجية': 'بەرهەمهێنان', 
      'تخصيص': 'ڕێکخستن', 'نمط حياة': 'شێوازی ژیان', 'فن وتصميم': 'هونەر و دیزاین', 'تصميم': 'دیزاین', 'أمن': 'ئاسایش', 
      'نظام': 'سیستەم', 'محاكيات': 'لێکچووەکان', 'متصفحات': 'وێبگەڕەکان', 'تخزين': 'هەڵگرتن', 'أعمال': 'کار', 
      'ترفيه': 'کات بەسەربردن', 'مال': 'دارایی', 'صحة ولياقة': 'تەندروستی و لەشجوانی', 'طب': 'پزیشکی', 'أخبار': 'هەواڵ', 
      'طقس': 'کەشوهەوا', 'تسوّق': 'بازاڕکردن', 'سفر': 'گەشتکردن', 'تعليم': 'پەروەردە'
    },
    onboardingWelcome: 'بەخێربێیت بۆ iKyro!',
    onboardingNavDesc: 'ناویگەیشنی خوارەوە بەکاربهێنە بۆ خێرا گۆڕین لە نێوان یارییەکان، بەرنامەکان، گەڕان، و پڕۆفایلەکەت.',
    onboardingSearchDesc: 'بە خێرایی بەرنامە و یارییە دڵخوازەکانت بدۆزەرەوە بە بەکارهێنانی گەڕانی گشتگیرمان.',
    onboardingNext: 'دواتر',
    onboardingDone: 'تێگەیشتم!',
    exitConfirmTitle: 'دەرچوون لە بەرنامە',
    exitConfirmDesc: 'دڵنیایت دەتەوێت دەربچیت؟',
    exitConfirmYes: 'دەرچوون',
    exitConfirmNo: 'پاشگەزبوونەوە',
    instantGames: 'یارییە خێراکان',
    playNow: 'ئێستا یاری بکە',
    ticTacToe: 'تیک تاک تۆ',
    simonSays: 'سایمۆن دەڵێت',
    memoryGame: 'یاری بیرەوەری',
    starCatcher: 'ڕاوکەری ئەستێرە',
    rockPaperScissors: 'بەرد کاغەز مقەست',
    youWin: 'تۆ بردەوە!',
    youLose: 'تۆ دۆڕایت!',
    draw: 'یەکسانبوون!'
  }
};

